### ISSUE TITLE
bing接入点的OpenAI API支持

### ISSUE THREAD

**Issue by luckyEason** [Nothingness-Void/Public-bing-chatgpt-proxy#10]
bing接入点是否支持OpenAI API格式的请求？

**Comment by Nothingness-Void** [comment]
> bing接入点是否支持OpenAI API格式的请求？

支持的 请求格式和OpenAI官方一样 模型参考https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI

**Comment by luckyEason** [comment]
可以了，就是延迟有点高，长对话会超时
