### ISSUE TITLE
CA and CA2 can't be used anymore

### ISSUE THREAD

**Issue by X-WuMing** [Nothingness-Void/Public-bing-chatgpt-proxy#11]
CA can't be used anymore，hint like this
![1](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/112425696/3981827a-d8ab-49c6-b980-b4d26787643f)
CA2 can't be used anymore，hint like this
![2](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/112425696/7a81e54e-f0bf-4ce4-a992-795e5ce27b97)

**Comment by Nothingness-Void** [comment]
> CA can't be used anymore，hint like this ![1](https://private-user-images.githubusercontent.com/112425696/304077926-3981827a-d8ab-49c6-b980-b4d26787643f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc3OTI2LTM5ODE4MjdhLWQ4YWItNDljNi1iOTgwLWI0ZDI2Nzg3NjQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzVlZjk5Y2U0NDNlZTJlZmVhNTRjNGRlMDcyZGEyODY2MjIwNzhhMGU2YjI4NjMwMjczOTc4OTY3ODk5OGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7lacU8x_6DpNSVLQwkweDqCYdtzNClqWRbTODGhrf4s) CA2 can't be used anymore，hint like this ![2](https://private-user-images.githubusercontent.com/112425696/304078148-7a81e54e-f0bf-4ce4-a992-795e5ce27b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc4MTQ4LTdhODFlNTRlLWYwYmYtNGNlNC1hOTkyLTc5NWU1Y2UyN2I5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGM4NTVmN2EyZmFmODQ3YTFiNTMzZTllZGE4ODQ3Y2Y5ODM4MjJjZmI5YTYzNmIzNTc1MzQ0MDI0ZmE0MjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WEzT2hOyNC5i12Kfy8TqltSiQfx2WBfnGlNQpMbAYmE)

目前应该可用了，但上游项目已经停止更新，我也不确定能支持到什么时候

**Comment by X-WuMing** [comment]
> > CA不能再用了，这样提示![1](https://private-user-images.githubusercontent.com/112425696/304077926-3981827a-d8ab-49c6-b980-b4d26787643f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc3OTI2LTM5ODE4MjdhLWQ4YWItNDljNi1iOTgwLWI0ZDI2Nzg3NjQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzVlZjk5Y2U0NDNlZTJlZmVhNTRjNGRlMDcyZGEyODY2MjIwNzhhMGU2YjI4NjMwMjczOTc4OTY3ODk5OGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7lacU8x_6DpNSVLQwkweDqCYdtzNClqWRbTODGhrf4s)CA2不能再用了，这样提示![2](https://private-user-images.githubusercontent.com/112425696/304078148-7a81e54e-f0bf-4ce4-a992-795e5ce27b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc4MTQ4LTdhODFlNTRlLWYwYmYtNGNlNC1hOTkyLTc5NWU1Y2UyN2I5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGM4NTVmN2EyZmFmODQ3YTFiNTMzZTllZGE4ODQ3Y2Y5ODM4MjJjZmI5YTYzNmIzNTc1MzQ0MDI0ZmE0MjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WEzT2hOyNC5i12Kfy8TqltSiQfx2WBfnGlNQpMbAYmE)
> 
> 目前应该可用了,但上游项目已经停止更新,我也不确定能支持到什么时候

不行，全部都不行，你主机去试试再说

**Comment by Nothingness-Void** [comment]
> > > CA不能再用了，这样提示![1](https://private-user-images.githubusercontent.com/112425696/304077926-3981827a-d8ab-49c6-b980-b4d26787643f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc3OTI2LTM5ODE4MjdhLWQ4YWItNDljNi1iOTgwLWI0ZDI2Nzg3NjQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzVlZjk5Y2U0NDNlZTJlZmVhNTRjNGRlMDcyZGEyODY2MjIwNzhhMGU2YjI4NjMwMjczOTc4OTY3ODk5OGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7lacU8x_6DpNSVLQwkweDqCYdtzNClqWRbTODGhrf4s)CA2不能再用了，这样提示![2](https://private-user-images.githubusercontent.com/112425696/304078148-7a81e54e-f0bf-4ce4-a992-795e5ce27b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc4MTQ4LTdhODFlNTRlLWYwYmYtNGNlNC1hOTkyLTc5NWU1Y2UyN2I5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGM4NTVmN2EyZmFmODQ3YTFiNTMzZTllZGE4ODQ3Y2Y5ODM4MjJjZmI5YTYzNmIzNTc1MzQ0MDI0ZmE0MjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WEzT2hOyNC5i12Kfy8TqltSiQfx2WBfnGlNQpMbAYmE)
> > 
> > 
> > 目前应该可用了,但上游项目已经停止更新,我也不确定能支持到什么时候
> 
> 不行，全部都不行，你主机去试试再说

就是试了才跟你说的
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/489ba7ea-a000-420c-b4c5-e789c6564655)
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/6ce16a08-e92e-4648-bac7-6448b2d2e58f)
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/0da26fd2-b037-4708-8318-9c09188e14d2)

**Comment by X-WuMing** [comment]
> > > > CA不能再用了，这样提示![1](https://private-user-images.githubusercontent.com/112425696/304077926-3981827a-d8ab-49c6-b980-b4d26787643f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc3OTI2LTM5ODE4MjdhLWQ4YWItNDljNi1iOTgwLWI0ZDI2Nzg3NjQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzVlZjk5Y2U0NDNlZTJlZmVhNTRjNGRlMDcyZGEyODY2MjIwNzhhMGU2YjI4NjMwMjczOTc4OTY3ODk5OGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7lacU8x_6DpNSVLQwkweDqCYdtzNClqWRbTODGhrf4s)CA2不能再用了，这样提示![2](https://private-user-images.githubusercontent.com/112425696/304078148-7a81e54e-f0bf-4ce4-a992-795e5ce27b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU3NTAsIm5iZiI6MTcwNzc0NTQ1MCwicGF0aCI6Ii8xMTI0MjU2OTYvMzA0MDc4MTQ4LTdhODFlNTRlLWYwYmYtNGNlNC1hOTkyLTc5NWU1Y2UyN2I5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGM4NTVmN2EyZmFmODQ3YTFiNTMzZTllZGE4ODQ3Y2Y5ODM4MjJjZmI5YTYzNmIzNTc1MzQ0MDI0ZmE0MjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WEzT2hOyNC5i12Kfy8TqltSiQfx2WBfnGlNQpMbAYmE)
> > > 
> > > 
> > > 目前应该可用了,但上游项目已经停止更新,我也不确定能支持到什么时候
> > 
> > 
> > 不行，全部都不行，你主机去试试再说
> 
> 就是试了才跟你说的 ![image](https://private-user-images.githubusercontent.com/55913486/304303084-489ba7ea-a000-420c-b4c5-e789c6564655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDM1NTQsIm5iZiI6MTcwNzgwMzI1NCwicGF0aCI6Ii81NTkxMzQ4Ni8zMDQzMDMwODQtNDg5YmE3ZWEtYTAwMC00MjBjLWI0YzUtZTc4OWM2NTY0NjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA1NDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTk1YmM2NjBhYWE2NjQxZDM4ZmY5Y2Q3NWUwZDQ5YjdiNzA5NTY2OTc0ZGE1NGVlYjY1OWY5NmJmYTAwMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KBx202TY-5fKOxbBi5rqExhwIxGpJDuy2SEAldeXDr0) ![image](https://private-user-images.githubusercontent.com/55913486/304303135-6ce16a08-e92e-4648-bac7-6448b2d2e58f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDM1NTQsIm5iZiI6MTcwNzgwMzI1NCwicGF0aCI6Ii81NTkxMzQ4Ni8zMDQzMDMxMzUtNmNlMTZhMDgtZTkyZS00NjQ4LWJhYzctNjQ0OGIyZDJlNThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA1NDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOTBkZDA0MGQ1MTNlYjRjZjAwZGUzYTQxYzU1NDZmN2Q2ZDMzZmJiNTdhZDZjNzRlNTY3YmVkZWRiM2UyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RAJlvRt9d4LGhiUb-lJ7JKDf87BPzxTTE9xHvJ7oS8M) ![image](https://private-user-images.githubusercontent.com/55913486/304303207-0da26fd2-b037-4708-8318-9c09188e14d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDM1NTQsIm5iZiI6MTcwNzgwMzI1NCwicGF0aCI6Ii81NTkxMzQ4Ni8zMDQzMDMyMDctMGRhMjZmZDItYjAzNy00NzA4LTgzMTgtOWMwOTE4OGUxNGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA1NDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNmYwODZhYzQ5MTc2NzZlMmM0YzExYmJiYzNhODhkNjAxOGExNjIxYTZiODFiNmNmMTIyMmQ2YmFjZDYwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NgBrqaBeMtoQEamkI5ZAQ9wcPwSCZ028X-DJGtg-iE)

我用的是https://fakeopen-ca.nvoid.me/backend-api/conversation，多了conversation，一开始可以，但这几天就不行了
