### ISSUE TITLE
网页版可以登录，但GPT无回应

### ISSUE THREAD

**Issue by CharlesQwQ** [Nothingness-Void/Public-bing-chatgpt-proxy#12]
问题同https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/issues/4，
现有的两个节点均无回应。

**Comment by Nothingness-Void** [comment]
第一个
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/98f61b79-78a6-46fb-a232-358fda97d4f3)
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/6d5bb3b2-ee9e-4094-940c-3e59e796153a)
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/dd3e0e10-3362-4e3c-a8d2-3c0bdaaa064e)

第二个
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/55e7494c-9cd5-4336-b58c-f13f2950c5c6)
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/1d0fc6b1-542f-4b96-902b-2f6a4496e1c2)
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/4850b4d0-e289-4a98-8072-8841691102a0)

**Comment by CharlesQwQ** [comment]
已尝试，尚未解决
[openai]
browserless_endpoint = "https://fakeopen-jp2.nvoid.pp.ua/backend-api/"
相关设置如上

梯子开的是v2ray，whitelist，已配置代理 proxy="http://127.0.0.1:10809"（不知道是不是这个有问题qwq）
希望大佬解答

> 第一个 ![image](https://private-user-images.githubusercontent.com/55913486/307500921-98f61b79-78a6-46fb-a232-358fda97d4f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTgzMzYsIm5iZiI6MTcwODc1ODAzNiwicGF0aCI6Ii81NTkxMzQ4Ni8zMDc1MDA5MjEtOThmNjFiNzktNzhhNi00NmZiLWEyMzItMzU4ZmRhOTdkNGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzA3N2ZmYjYwNmZhMzliMjExODc3OGJiODZmYzE5ODc2MWI3MGUxMDZmYmNhZDVkNDc3MGY4NmQ1MGE1OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3DvJ0jKSkrNcMbwswdhEykVeBNeQJ4RShKyydKQgT3o) ![image](https://private-user-images.githubusercontent.com/55913486/307500928-6d5bb3b2-ee9e-4094-940c-3e59e796153a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTgzMzYsIm5iZiI6MTcwODc1ODAzNiwicGF0aCI6Ii81NTkxMzQ4Ni8zMDc1MDA5MjgtNmQ1YmIzYjItZWU5ZS00MDk0LTk0MGMtM2U1OWU3OTYxNTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODI2YjZhZTBjMzhjMGExNzYwNTY5MjFlNzE5M2ZlY2EwMTJmY2MwMzY1NGMwNTRjNDc5ZjM2ZTgyZTNhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mLEXnwJX29mY9nZUX3eeefn2L3J-qT_M99J4z62P85M) ![image](https://private-user-images.githubusercontent.com/55913486/307500944-dd3e0e10-3362-4e3c-a8d2-3c0bdaaa064e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTgzMzYsIm5iZiI6MTcwODc1ODAzNiwicGF0aCI6Ii81NTkxMzQ4Ni8zMDc1MDA5NDQtZGQzZTBlMTAtMzM2Mi00ZTNjLWE4ZDItM2MwYmRhYWEwNjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NmUyZTk5OWIyZDE2MjhlNDg2MDVmN2U3OGFlYjRmY2RkMTNhZGU5MWRmZjE5Mzk4MDI2YzMxNWNkODQ1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ba_DFUk4e7moMusHNdq17HCT7UZCwI1ixwyx-n2CrbU)
> 
> 第二个 ![image](https://private-user-images.githubusercontent.com/55913486/307501030-55e7494c-9cd5-4336-b58c-f13f2950c5c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTgzMzYsIm5iZiI6MTcwODc1ODAzNiwicGF0aCI6Ii81NTkxMzQ4Ni8zMDc1MDEwMzAtNTVlNzQ5NGMtOWNkNS00MzM2LWI1OGMtZjEzZjI5NTBjNWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTNiMTc4MGQ1YjhiZGExNWQxZTg2ZWJlMDU0OGE4MzViNWI5M2I4ZDNjZjg0NzkxNmZjYmY2ZTRjOTdjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAz_pl-e9wDGyWbrGJb9Hw5haLBll6WWV-S_04JgIWA) ![image](https://private-user-images.githubusercontent.com/55913486/307501072-1d0fc6b1-542f-4b96-902b-2f6a4496e1c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTgzMzYsIm5iZiI6MTcwODc1ODAzNiwicGF0aCI6Ii81NTkxMzQ4Ni8zMDc1MDEwNzItMWQwZmM2YjEtNTQyZi00Yjk2LTkwMmItMmY2YTQ0OTZlMWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMWNhNGVjNmYwNjRlZTMzNGRhZWZmNTZlNWZkNDhmZjg0ODE2MTQ4MTc5YjM3YmU5N2QwMTU3MWM0MjkyYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZU9G0So2JNmT7k3tUIFtxqhOmcBFDitl1XEZ8CsmCqA) ![image](https://private-user-images.githubusercontent.com/55913486/307501081-4850b4d0-e289-4a98-8072-8841691102a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTgzMzYsIm5iZiI6MTcwODc1ODAzNiwicGF0aCI6Ii81NTkxMzQ4Ni8zMDc1MDEwODEtNDg1MGI0ZDAtZTI4OS00YTk4LTgwNzItODg0MTY5MTEwMmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA3MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzFiZDYzZTVhNGFiYzEwZGFlNTYzODc1NmQyMzhmODBkMmNjMjZlM2M1YWI1NjM0MTM1OWU2ZmJkNDRkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ZgBzcdsq-boiQrJ6JeIygCQiFndqtUd0ByKuDM1J0U)

**Comment by CharlesQwQ** [comment]
现更换成api接入，已解决
