### ISSUE TITLE
接入点貌似用不了了

### ISSUE THREAD

**Issue by pp0915** [Nothingness-Void/Public-bing-chatgpt-proxy#3]
接入点貌似gg了
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/135289054/baf132df-ebbb-4f94-9614-8d092a02e0b6)

**Comment by Nothingness-Void** [comment]
测试可用 
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/5a4fe480-d7bc-4b42-9a3e-24aba30caf08)
我前两天也出问题 换cookie就好了
