### ISSUE TITLE
openai的网页版api可以登录，但GPT无回应

### ISSUE THREAD

**Issue by WinstonDeSun** [Nothingness-Void/Public-bing-chatgpt-proxy#4]
您好，您提供的公共openai的网页版api可以登录，但GPT无回应，显示排到了后一直未响应直到报错。

**Comment by Nothingness-Void** [comment]
我本人也遇到这个问题了，周末研究一下 今天还要上课

**Comment by Nothingness-Void** [comment]
已更新新的能用的，但是不保稳

**Comment by WinstonDeSun** [comment]
您好，谢谢您提供接入点，我试过新的三个接入点，还是无法回应消息

**Comment by Nothingness-Void** [comment]
我试过确实能用啊 
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/93fe48c9-c0c4-4d5d-b211-c2e22c27aff0)
你看看他结构是不一样的
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/55913486/9d979782-d261-4311-8bed-23d7fc53286a)
是不是输错了

**Comment by WinstonDeSun** [comment]
谢谢您，问题已解决，再次感谢您无私奉献!

Nothingness-Void ***@***.***> 於 2023年10月27日 週五 17:55 寫道：
