### ISSUE TITLE
openai网页端第一个接入点有bug

### ISSUE THREAD

**Issue by GTian28** [Nothingness-Void/Public-bing-chatgpt-proxy#5]
**Describe the bug**
https://fakeopen-ca.nvoid.me/backend-api/
这个接入点有bug，登录没问题。聊天会报错。实测第二个接入点就一切正常。

**Expected behavior**
正常聊天对话

**Screenshots**
![image](https://github.com/Nothingness-Void/Public-bing-chatgpt-proxy/assets/115866194/7552402f-a2b0-4642-ad75-67cc3a7dcf2b)

**Comment by Nothingness-Void** [comment]
已修复

**Comment by GTian28** [comment]
> 已修复

试了一下确实没问题了，效率太高了！感谢
